services:
  khzs:
    build: .
    container_name: khzs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
